// Master Thai translation dictionary for admin UI chrome.
// All hardcoded English strings in admin components map to a key here.
// Dynamic strings (with interpolation) are typed as functions.

export const th = {
  // ── Shell / Navigation ──────────────────────────────────────────────────
  navGroupMain:        "หลัก",
  navGroupSettings:    "การตั้งค่า",
  navDashboard:        "แดชบอร์ด",
  navProducts:         "สินค้า",
  navContent:          "คอนเทนต์",
  navSlides:           "สไลด์หน้าแรก",
  navProfile:          "โปรไฟล์",
  navPublicSite:       "ดูเว็บไซต์",
  navSignOut:          "ออกจากระบบ",
  shellBrand:          "SP Admin",
  shellSubBrand:       "สยาม พรีเมียม",
  shellLogoAlt:        "โลโก้ SP",
  shellSettingsTitle:  "การตั้งค่า",
  shellProfileMenu:    "ตั้งค่าโปรไฟล์",
  shellSignOutMenu:    "ออกจากระบบ",
  shellPageAdmin:      "แอดมิน",

  // ── Dashboard ───────────────────────────────────────────────────────────
  greetMorning:        "สวัสดีตอนเช้า",
  greetAfternoon:      "สวัสดีตอนบ่าย",
  greetEvening:        "สวัสดีตอนเย็น",
  dashSubtitle:        "สรุปภาพรวมวันนี้",
  dashStatTotal:       "สินค้าทั้งหมด",
  dashStatVisible:     "แสดงอยู่",
  dashStatNew:         "สินค้าใหม่",
  dashStatCats:        "หมวดหมู่",
  dashRecent:          "สินค้าล่าสุด",
  dashTopCats:         "หมวดหมู่ยอดนิยม",
  dashQuickActions:    "ดำเนินการด่วน",
  dashNoProducts:      "ยังไม่มีสินค้า",
  dashViewAll:         "ดูสินค้าทั้งหมด →",
  dashAddNew:          "+ เพิ่มสินค้าใหม่",
  dashViewProducts:    "ดูรายการสินค้า",
  statusActive:        "แสดง",
  statusHidden:        "ซ่อน",

  // ── Products list ───────────────────────────────────────────────────────
  productsHeading:     "สินค้า",
  productsAddBtn:      "+ เพิ่มสินค้า",
  productsLoadFail:    "โหลดสินค้าไม่สำเร็จ",
  productsSearch:      "ค้นหาสินค้า...",
  productsFilterAll:   "ทั้งหมด",
  productsColImage:    "รูปภาพ",
  productsColName:     "ชื่อสินค้า",
  productsColCat:      "หมวดหมู่",
  productsColTags:     "แท็ก",
  productsColOrder:    "ลำดับ",
  productsColStatus:   "สถานะ",
  productsColActions:  "การจัดการ",
  productsBulkSoon:    "เลือกหลายรายการ (เร็วๆ นี้)",
  productsClickHide:   "คลิกเพื่อซ่อน",
  productsClickShow:   "คลิกเพื่อแสดง",
  productsEdit:        "แก้ไข",
  productsDelete:      "ลบ",
  productsDeleteQ:     "ยืนยันลบ?",
  productsYes:         "ใช่",
  productsNo:          "ไม่",
  productsPrev:        "ก่อนหน้า",
  productsNext:        "ถัดไป",
  productsEmpty:       "ยังไม่มีสินค้า",
  productsFirstAdd:    "เพิ่มสินค้าชิ้นแรก",
  productsNoMatch:     "ไม่พบสินค้าที่ค้นหา",
  productsDeleted:     "ลบสินค้าแล้ว",
  productsUpdateFail:  "อัปเดตสินค้าไม่สำเร็จ",
  productsDeleteFail:  "ลบสินค้าไม่สำเร็จ",
  productsHiddenToast: (name: string) => `"${name}" ซ่อนแล้ว`,
  productsVisibleToast:(name: string) => `"${name}" แสดงแล้ว`,
  productsShowing:     (n: number, total: number) => `แสดง ${n} จาก ${total} รายการ`,
  productsPagination:  (s: number, e: number, t: number) => `แสดง ${s}–${e} จาก ${t}`,
  productsSubtitle:    (total: number, active: number, isNew: number) =>
    `${total} รายการ · ${active} แสดง · ${isNew} ใหม่`,

  // ── Product form ────────────────────────────────────────────────────────
  formAdd:             "เพิ่มสินค้า",
  formEdit:            "แก้ไขสินค้า",
  formCardBasic:       "ข้อมูลพื้นฐาน",
  formCardDesc:        "คำอธิบาย",
  formCardTags:        "แท็ก",
  formCardImages:      "รูปภาพ",
  formCardBranding:    "การพิมพ์โลโก้",
  formCardVisibility:  "การแสดงผล",
  formNameEn:          "ชื่อสินค้า (อังกฤษ) *",
  formNameTh:          "ชื่อสินค้า (ไทย)",
  formCategory:        "หมวดหมู่ *",
  formOrder:           "ลำดับการแสดง",
  formDescEn:          "คำอธิบาย (อังกฤษ)",
  formDescTh:          "คำอธิบาย (ไทย)",
  formBrandingMethods: "วิธีการพิมพ์โลโก้",
  formMoq:             "MOQ",
  formVisible:         "แสดงในแคตาล็อก",
  formMarkNew:         "ทำเครื่องหมายว่าใหม่",
  formOrderHint:       "ตัวเลขน้อย = แสดงก่อน",
  formTagsHint:        "ใช้สำหรับกรองในหน้าแคตาล็อก หากต้องการเพิ่มหรือเปลี่ยนชื่อแท็ก ไปที่",
  formTagsLink:        "ตั้งค่าคอนเทนต์",
  formImagesHint:      "ช่องแรก = ภาพหลัก อัปโหลดได้สูงสุด 10 รูป",
  formMoqHint:         "แสดงให้ลูกค้าเห็นในฐานะจำนวนขั้นต่ำต่อออร์เดอร์",
  formVisibleDesc:     "แสดงสินค้านี้แก่ลูกค้า",
  formNewDesc:         "แสดงป้าย \"ใหม่\" บนสินค้า",
  formImageMain:       "หลัก",
  formSelectTags:      "เลือกแท็ก…",
  formNoTags:          "ยังไม่มีแท็ก — เพิ่มได้ที่ตั้งค่าคอนเทนต์",
  formSaveBarNew:      "สินค้าใหม่ — ยังไม่ได้บันทึก",
  formSaveBarUnsaved:  "มีการแก้ไขที่ยังไม่บันทึก",
  formSaveBarJustNow:  "บันทึกล่าสุด: เมื่อกี้นี้",
  formSaveBarMinutes:  (n: number) => `บันทึกล่าสุด: ${n} นาทีที่แล้ว`,
  formCancel:          "ยกเลิก",
  formSaving:          "กำลังบันทึก…",
  formAddBtn:          "เพิ่มสินค้า",
  formSaveBtn:         "บันทึกสินค้า",
  formRendersAs:       "แสดงผลเป็น:",
  toastProductCreated: "เพิ่มสินค้าสำเร็จ!",
  toastProductSaved:   "บันทึกสินค้าสำเร็จ!",
  toastImg5MB:         "รูปภาพต้องมีขนาดไม่เกิน 5 MB",
  toastImg10MB:        "รูปภาพต้องมีขนาดไม่เกิน 10 MB",
  toastUploadFail:     (msg: string) => `อัปโหลดไม่สำเร็จ: ${msg}`,
  toastProductFail:    "บันทึกสินค้าไม่สำเร็จ",
  brandingLogoPrint:   "พิมพ์โลโก้",
  brandingLaser:       "เลเซอร์แกะสลัก",
  brandingEmbroidery:  "ปักโลโก้",
  brandingScreen:      "สกรีนพิมพ์",

  // ── Slides list ─────────────────────────────────────────────────────────
  slidesHeading:       "สไลด์หน้าแรก",
  slidesSubtitle:      (n: number) => `ลาก-วางเพื่อเรียงลำดับ · สลับเพื่อแสดง/ซ่อน · ${n} สไลด์`,
  slidesAddBtn:        "เพิ่มสไลด์",
  slidesLoadFail:      "โหลดสไลด์ไม่สำเร็จ",
  slidesEmpty:         "ยังไม่มีสไลด์",
  slidesFirstAdd:      "เพิ่มสไลด์แรก",
  slidesSavingOrder:   "กำลังบันทึกลำดับ…",
  slidesNoHeading:     "(ไม่มีหัวเรื่อง)",
  slidesHidden:        "ซ่อน",
  slidesClickHide:     "คลิกเพื่อซ่อน",
  slidesClickShow:     "คลิกเพื่อแสดง",
  slidesEdit:          "แก้ไข",
  slidesDelete:        "ลบ",
  slidesDeleteQ:       "ยืนยันลบ?",
  slidesYes:           "ใช่",
  slidesNo:            "ไม่",
  toastOrderSaved:     "บันทึกลำดับแล้ว",
  toastOrderFail:      "บันทึกลำดับไม่สำเร็จ",
  toastSlideDeleted:   "ลบสไลด์แล้ว",
  toastSlideFail:      "อัปเดตไม่สำเร็จ",
  toastSlideDeleteFail:"ลบไม่สำเร็จ",
  toastSlideHidden:    (h: string) => `"${h}" ซ่อนแล้ว`,
  toastSlideVisible:   (h: string) => `"${h}" แสดงแล้ว`,

  // ── Slide new / edit pages ───────────────────────────────────────────────
  slideNewHeading:     "สไลด์ใหม่",
  slideNewSub:         "กรอกเนื้อหาสไลด์ แล้วคลิก สร้างสไลด์",
  slideEditPrefix:     "แก้ไขสไลด์ —",

  // ── SlideForm ───────────────────────────────────────────────────────────
  sfCardContent:       "เนื้อหาสไลด์",
  sfCardCTA:           "ปุ่มเรียกร้องให้ดำเนินการ",
  sfCardBg:            "ภาพพื้นหลัง",
  sfCardStatus:        "สถานะ",
  sfCardOrder:         "ลำดับการแสดง",
  sfBadge:             "ป้ายกำกับ / ข้อความบน",
  sfHeading:           "หัวเรื่อง",
  sfSubheadline:       "หัวข้อรองตัวเอียงสีทอง",
  sfSubtext:           "ข้อความภาษาไทย",
  sfDescription:       "คำอธิบาย",
  sfBtnLabel:          "ข้อความปุ่ม",
  sfBtnLink:           "ลิงก์",
  sfBtn1Head:          "ปุ่มหลัก (พื้นทอง)",
  sfBtn2Head:          "ปุ่มรอง (เส้นขอบ)",
  sfBgReplace:         "เปลี่ยนรูป",
  sfBgRemove:          "นำออก",
  sfBgRecommended:     "แนะนำ: 1920×1080px (16:9)",
  sfBgUploading:       "กำลังอัปโหลด…",
  sfBgClickUpload:     "คลิกเพื่ออัปโหลดภาพพื้นหลัง",
  sfStatusActive:      "แสดง",
  sfStatusHidden:      "ซ่อน",
  sfStatusActiveDesc:  "แสดงในหน้าแรก",
  sfStatusHiddenDesc:  "ไม่แสดงในหน้าแรก",
  sfOrderHint:         "ตัวเลขน้อยกว่า = แสดงก่อน ลากแถวในรายการเพื่อเรียงลำดับ",
  sfBackBtn:           "← กลับ",
  sfDiscard:           "ยกเลิก",
  sfSaving:            "กำลังบันทึก…",
  sfCreate:            "สร้างสไลด์",
  sfSaveChanges:       "บันทึกการเปลี่ยนแปลง",
  sfHeadingRequired:   "กรุณากรอกหัวเรื่อง",
  toastImageUploaded:  "อัปโหลดรูปภาพแล้ว",
  toastSlideCreated:   "สร้างสไลด์แล้ว",
  toastChangesSaved:   "บันทึกการเปลี่ยนแปลงแล้ว",
  toastSaveFail:       "บันทึกไม่สำเร็จ",

  // ── StyleOverride ───────────────────────────────────────────────────────
  styleColor:          "สี",
  styleBg:             "พื้นหลัง",
  styleBorder:         "ขอบ",
  styleSize:           "ขนาด",
  styleFont:           "ฟอนต์",
  styleFontDefault:    "ค่าเริ่มต้น (Georgia)",
  styleReset:          "↩ รีเซ็ต",
  styleResetTitle:     (label: string) => `รีเซ็ต ${label} เป็นค่าเริ่มต้น`,
  stylePickColor:      (caption: string) => `เลือกสี ${caption}`,

  // ── Repeater ────────────────────────────────────────────────────────────
  repAddItem:          "เพิ่มรายการ",
  repMoveUp:           "ขึ้น",
  repMoveDown:         "ลง",
  repDelete:           "ลบ",
  repRemoveConfirm:    "ต้องการลบรายการนี้?",
  repItemFallback:     (n: number) => `รายการ ${n}`,

  // ── Content editor (tabs / shared) ──────────────────────────────────────
  contentHeading:      "คอนเทนต์",
  contentTabHome:      "หน้าแรก",
  contentTabCatalog:   "แคตาล็อก",
  contentTabAbout:     "เกี่ยวกับ",
  contentTabServices:  "บริการ",
  contentTabWork:      "ผลงาน",
  contentTabContact:   "ติดต่อ",
  contentTabFooter:    "ส่วนท้าย",
  contentTabBranding:  "แบรนด์",
  contentPageHome:     "หน้าแรก",
  contentPageCatalog:  "หน้าแคตาล็อก",
  contentPageAbout:    "หน้าเกี่ยวกับ",
  contentPageServices: "หน้าบริการ",
  contentPageWork:     "หน้าผลงาน",
  contentPageContact:  "หน้าติดต่อ",
  contentPageFooter:   "ส่วนท้าย",
  contentPageBranding: "แบรนด์ & โลโก้",
  contentSections:     "ส่วน",
  contentVisible:      "แสดง",
  contentHidden:       "ซ่อน",
  contentClickHide:    "แสดง — คลิกเพื่อซ่อน",
  contentClickShow:    "ซ่อน — คลิกเพื่อแสดง",
  contentFields:       (n: number) => `${n} ฟิลด์`,
  // Home — stat badges section
  secStatBadges:       "ตัวเลขสถิติ",
  secStatBadgesDesc:   "ตัวเลขสถิติ 3 ตัวใต้สไลด์หน้าแรก",
  secMarquee:          "ข้อความวิ่ง",
  secMarqueeDesc:      "ข้อความวิ่งผ่านหน้าเว็บ",
  secProcess:          "กระบวนการผลิต",
  secProcessDesc:      "กระบวนการผลิตแบบ step-by-step 5 ขั้นตอน",
  secCatalog:          "ส่วนแคตาล็อก",
  secCatalogDesc:      "หัวเรื่อง คำอธิบาย และปุ่มสำหรับส่วนแคตาล็อก",
  // Home — field labels
  flStatN:             (n: number) => `สถิติที่ ${n}`,
  flStatNumber:        "ตัวเลข",
  flStatLabelEn:       "ป้ายกำกับ (อังกฤษ)",
  flStatLabelTh:       "ป้ายกำกับ (ไทย)",
  flStatStyleNote:     "สไตล์ร่วมสำหรับสถิติทั้ง 3 ตัว",
  flMarqueeEn:         "รายการ — อังกฤษ (คั่นด้วยจุลภาค)",
  flMarqueeTh:         "รายการ — ไทย (คั่นด้วยจุลภาค)",
  flMarqueeHint:       "คั่นรายการด้วยเครื่องหมายจุลภาค เวอร์ชันไทยแสดงเมื่อภาษาเป็นไทย",
  flStyleOverrides:    "สไตล์",
  flProcHeadEn:        "หัวเรื่องส่วน (อังกฤษ)",
  flProcHeadTh:        "หัวเรื่องส่วน (ไทย)",
  flProcSubhead:       "หัวข้อรอง",
  flProcSteps:         "ขั้นตอน",
  flProcStyleNote:     "สไตล์ขั้นตอน — ใช้ร่วมกันทุก 5 ขั้นตอน",
  flProcStepTitleEn:   (n: number) => `ชื่อขั้นตอนที่ ${n} (อังกฤษ)`,
  flProcStepTitleTh:   (n: number) => `ชื่อขั้นตอนที่ ${n} (ไทย)`,
  flProcStepDesc:      (n: number) => `คำอธิบายขั้นตอนที่ ${n}`,
  flCatLabelEn:        "ป้ายกำกับส่วน (อังกฤษ)",
  flCatLabelTh:        "ป้ายกำกับส่วน (ไทย)",
  flCatHeadEn:         "หัวเรื่อง (อังกฤษ)",
  flCatHeadTh:         "หัวเรื่อง (ไทย)",
  flCatDescEn:         "คำอธิบาย (อังกฤษ)",
  flCatDescTh:         "คำอธิบาย (ไทย)",
  flCatQuoteEn:        "คำคม / แท็กไลน์ (อังกฤษ)",
  flCatQuoteTh:        "คำคม / แท็กไลน์ (ไทย)",
  flCatBtn1En:         "ปุ่ม 1 (อังกฤษ)",
  flCatBtn1Th:         "ปุ่ม 1 (ไทย)",
  flCatBtn2En:         "ปุ่ม 2 (อังกฤษ)",
  flCatBtn2Th:         "ปุ่ม 2 (ไทย)",
  // Save bar (shared across all content editors)
  saveUnsaved:         (section: string) => `มีการแก้ไขในส่วน ${section} ที่ยังไม่บันทึก`,
  saveDiscard:         "ยกเลิก",
  saveSaving:          "กำลังบันทึก…",
  saveBtn:             "บันทึก",
  saveFail:            "บันทึกไม่สำเร็จ กรุณาลองใหม่",

  // ── About editor ────────────────────────────────────────────────────────
  aboutLoading:        "กำลังโหลดหน้าเกี่ยวกับ…",
  aboutSecHero:        "ฮีโร่",
  aboutSecHeroDesc:    "หัวเรื่องและคำอธิบายส่วนฮีโร่",
  aboutSecStory:       "เรื่องราวของเรา",
  aboutSecStoryDesc:   "เนื้อหาเรื่องราว ป้ายกำกับ รายการตรวจสอบ และรูปทีม",
  aboutSecStats:       "สถิติ",
  aboutSecStatsDesc:   "การ์ดสถิติแบบนับขึ้น 4 ใบ",
  aboutSecMilestones:  "ไทม์ไลน์",
  aboutSecMilDesc:     "ไทม์ไลน์ประวัติบริษัท",
  aboutSecQuote:       "คำคม",
  aboutSecQuoteDesc:   "ส่วนคำคมปรัชญา",
  aboutHeroBadge:      "ป้ายกำกับ",
  aboutHeroHead:       "หัวเรื่อง (บรรทัดหลัก)",
  aboutHeroHeadIt:     "หัวเรื่อง (บรรทัดตัวเอียง)",
  aboutHeroSubtext:    "ข้อความภาษาไทย",
  aboutHeroDesc:       "ย่อหน้าคำอธิบาย",
  aboutStoryBadge:     "ป้ายกำกับ",
  aboutStoryClLabelEn: "หัวข้อรายการตรวจสอบ (อังกฤษ)",
  aboutStoryClLabelTh: "หัวข้อรายการตรวจสอบ (ไทย)",
  aboutStoryHead:      "หัวเรื่อง (บรรทัดหลัก)",
  aboutStoryHeadIt:    "หัวเรื่อง (บรรทัดตัวเอียง)",
  aboutStoryP1En:      "ย่อหน้า 1 (อังกฤษ)",
  aboutStoryP1Th:      "ย่อหน้า 1 (ไทย)",
  aboutStoryP2En:      "ย่อหน้า 2 (อังกฤษ)",
  aboutStoryP2Th:      "ย่อหน้า 2 (ไทย)",
  aboutStoryChecklist:  "รายการตรวจสอบ",
  aboutChecklistItem:   "ข้อความ",
  aboutStoryPhoto:     "รูปทีม (สัดส่วน 3:4)",
  aboutStoryCaption:   "คำบรรยายภาพ",
  aboutStatsNote:      "การ์ดสถิติแบบนับขึ้น 4 ใบ",
  aboutStatsCount:     "จำนวน (เช่น 25000)",
  aboutStatsSuffix:    "ต่อท้าย (เช่น +)",
  aboutStatsLabelEn:   "ป้ายกำกับ (อังกฤษ)",
  aboutStatsLabelTh:   "ป้ายกำกับ (ไทย)",
  aboutStatsBg:        "ข้อความพื้นหลัง (เช่น 3K+)",
  aboutStatsHint:      "\"จำนวน\" ต้องเป็นตัวเลข (เช่น 3000) ต่อท้ายจะแสดงหลังตัวเลข ป้ายกำกับแสดงด้านล่าง",
  aboutStatsAdd:       "เพิ่มสถิติ",
  aboutMilNote:        "ไทม์ไลน์เหตุการณ์",
  aboutMilYrShort:     "ปีย่อ (เช่น 03)",
  aboutMilYrFull:      "ปีเต็ม (เช่น 2003)",
  aboutMilTextEn:      "คำอธิบายเหตุการณ์ (อังกฤษ)",
  aboutMilTextTh:      "คำอธิบายเหตุการณ์ (ไทย)",
  aboutMilActive:      "ไฮไลต์ / ใช้งาน",
  aboutMilPhoto:       "รูปประวัติ (สัดส่วน 4:3)",
  aboutMilCaption:     "คำบรรยายภาพ",
  aboutMilAdd:         "เพิ่มเหตุการณ์",
  aboutQuoteLabel:     "ป้ายกำกับส่วน",
  aboutQuoteTextEn:    "ข้อความคำคม (อังกฤษ) — ไม่ต้องใส่เครื่องหมายคำพูด",
  aboutQuoteTextTh:    "ข้อความคำคม (ไทย) — ไม่ต้องใส่เครื่องหมายคำพูด",
  aboutQuoteAttr:      "ที่มา",
  // Shared image upload labels used in About
  imgNoImage:          "ไม่มีรูปภาพ",
  imgUpload:           "อัปโหลดรูปภาพ",
  imgReplace:          "เปลี่ยนรูป",
  imgRemove:           "นำออก",
  imgUploading:        "กำลังอัปโหลด…",
  imgHint:             "PNG, JPEG, หรือ WebP · สูงสุด 10 MB รูปภาพจะบันทึกเมื่อคลิก \"บันทึก\" ด้านล่าง",
  imgErrSize:          "รูปภาพต้องมีขนาดไม่เกิน 10 MB",
  imgErrUpload:        (msg: string) => `อัปโหลดไม่สำเร็จ: ${msg}`,

  // ── Services editor ─────────────────────────────────────────────────────
  servicesLoading:     "กำลังโหลดเนื้อหาบริการ…",
  svSecHero:           "ฮีโร่",
  svSecHeroDesc:       "ส่วนฮีโร่ของหน้า",
  svSecServices:       "บริการ",
  svSecServicesDesc:   "การ์ดบริการ 6 ใบ (เรียงตามลำดับ)",
  svSecWhy:            "ทำไมต้อง SP",
  svSecWhyDesc:        "ส่วนเหตุผลที่เลือก SP",
  svSecProcess:        "ขั้นตอน",
  svSecProcessDesc:    "กระบวนการผลิต 4 ขั้นตอน",
  svHeroBadge:         "ป้ายกำกับ / ข้อความบน",
  svHeroHead:          "หัวเรื่อง (หลัก)",
  svHeroHeadIt:        "หัวเรื่อง (ตัวเอียง)",
  svHeroSubtext:       "ข้อความภาษาไทย",
  svHeroDesc:          "คำอธิบาย",
  svCardsNote:         "การ์ดบริการ — รายการที่ 1–2 เป็นแถวใหญ่ รายการที่ 3–6 เป็นกริด",
  svNum:               "หมายเลข (เช่น 01)",
  svIcon:              "คลาสไอคอน Tabler",
  svTitleEn:           "ชื่อ (อังกฤษ)",
  svTitleTh:           "ชื่อ (ไทย)",
  svDescEn:            "คำอธิบาย (อังกฤษ)",
  svDescTh:            "คำอธิบาย (ไทย)",
  svFeatured:          "การ์ดเด่น (ใหญ่)",
  svAddService:        "เพิ่มบริการ",
  svWhyBadge:          "ป้ายกำกับส่วน",
  svWhyHead:           "หัวเรื่องส่วน",
  svWhyNum:            "หมายเลข",
  svWhyIcon:           "คลาสไอคอน",
  svWhyTitleEn:        "ชื่อ (อังกฤษ)",
  svWhyTitleTh:        "ชื่อ (ไทย)",
  svWhyDescEn:         "คำอธิบาย (อังกฤษ)",
  svWhyDescTh:         "คำอธิบาย (ไทย)",
  svAddReason:         "เพิ่มเหตุผล",
  svProcBadge:         "ป้ายกำกับส่วน",
  svProcHead:          "หัวเรื่องส่วน",
  svProcNum:           "หมายเลข",
  svProcIcon:          "คลาสไอคอน",
  svProcTitleEn:       "ชื่อ (อังกฤษ)",
  svProcTitleTh:       "ชื่อ (ไทย)",
  svProcDescEn:        "คำอธิบาย (อังกฤษ)",
  svProcDescTh:        "คำอธิบาย (ไทย)",
  svProcActive:        "ใช้งาน (วงกลมทอง)",
  svAddStep:           "เพิ่มขั้นตอน",

  // ── Our Work editor ─────────────────────────────────────────────────────
  owLoading:           "กำลังโหลดหน้าผลงาน…",
  owLoadingProjects:   "กำลังโหลดผลงาน…",
  owLoadFail:          "โหลดผลงานไม่สำเร็จ",
  owSecHero:           "ฮีโร่",
  owSecHeroDesc:       "ข้อความบนและหัวเรื่องหน้า",
  owSecStats:          "แถบสถิติ",
  owSecStatsDesc:      "ตัวเลขสถิติ 3 ตัวในฮีโร่",
  owSecProjects:       "ผลงาน",
  owSecProjectsDesc:   "การ์ดพอร์ตโฟลิโอ — เพิ่ม/แก้ไข/ลบ",
  owHeroBadge:         "ข้อความบน / ป้ายกำกับ",
  owHeroHead:          "หัวเรื่อง (หลัก)",
  owHeroHeadIt:        "หัวเรื่อง (ตัวเอียง)",
  owStatsNote:         "ตัวเลขสถิติ 3 ตัวที่ด้านล่างฮีโร่",
  owStatNum:           "ตัวเลข",
  owStatLabel:         "ป้ายกำกับ",
  owStatsAdd:          "เพิ่มสถิติ",
  owProjectsHint:      "ฟิลด์ \"ลูกค้า\" จะแสดงเป็นป้ายกำกับบนการ์ด ผลงานแสดงตามลำดับที่กำหนด",
  owProjectHidden:     "ซ่อน",
  owMoveUp:            "ขึ้น",
  owMoveDown:          "ลง",
  owDelete:            "ลบ",
  owClient:            "ลูกค้า (กุญแจกรอง)",
  owAspect:            "สัดส่วน",
  owTitleEn:           "ชื่อโปรเจกต์ (อังกฤษ)",
  owTitleTh:           "ชื่อโปรเจกต์ (ไทย)",
  owDesc:              "คำอธิบาย",
  owImage:             "รูปภาพ",
  owTags:              "แท็ก (คั่นด้วยจุลภาค)",
  owIcon:              "คลาสไอคอน (ไม่มีรูป)",
  owLink:              "ลิงก์โปรเจกต์ (ถ้ามี)",
  owMetrics:           "Metrics JSON (แสดงในป๊อปอัป)",
  owVisible:           "แสดงในเว็บไซต์",
  owAspectTall:        "สูง (3:4)",
  owAspectWide:        "กว้าง (4:3)",
  owAspectSquare:      "สี่เหลี่ยม (1:1)",
  owSaving:            "กำลังบันทึก…",
  owSaveProject:       "บันทึกผลงาน",
  owAddProject:        "+ เพิ่มผลงาน",
  toastProjectSaved:   "บันทึกผลงานแล้ว",
  toastProjectDeleted: "ลบผลงานแล้ว",
  toastProjectAdded:   "เพิ่มผลงานใหม่แล้ว — กรอกรายละเอียดและบันทึก",
  owErrSave:           (msg: string) => `บันทึกไม่สำเร็จ: ${msg}`,
  owErrDelete:         (msg: string) => `ลบไม่สำเร็จ: ${msg}`,
  owErrAdd:            (msg: string) => `เพิ่มไม่สำเร็จ: ${msg}`,
  owErrReorder:        (msg: string) => `เรียงลำดับไม่สำเร็จ: ${msg}`,
  owErrUpload:         (msg: string) => `อัปโหลดไม่สำเร็จ: ${msg}`,
  owProjCount:         (n: number) => `${n} ผลงาน`,
  owDeleteConfirm:     "ลบผลงานนี้ถาวร?",
  owImgReplace:        "เปลี่ยนรูป",
  owImgRemove:         "นำออก",
  owImgUploading:      "กำลังอัปโหลด…",
  owImgClick:          "คลิกเพื่ออัปโหลดรูปภาพ",

  // ── Contact editor ──────────────────────────────────────────────────────
  contactLoading:      "กำลังโหลดหน้าติดต่อ…",
  ctSecHero:           "ฮีโร่",
  ctSecHeroDesc:       "ป้ายกำกับและคำอธิบายฮีโร่",
  ctSecInfo:           "ข้อมูลติดต่อ",
  ctSecInfoDesc:       "โทรศัพท์ อีเมล ที่อยู่ เวลาทำการ",
  ctSecSocial:         "โซเชียลมีเดีย",
  ctSecSocialDesc:     "URL โซเชียลมีเดีย",
  ctSecMap:            "แผนที่",
  ctSecMapDesc:        "ป้ายกำกับ หัวข้อ และปุ่มส่วนแผนที่",
  ctHeroBadge:         "ป้ายกำกับ / ข้อความบน",
  ctHeroHead:          "หัวเรื่อง",
  ctHeroSubtext:       "ข้อความภาษาไทย",
  ctHeroDesc:          "คำอธิบาย",
  ctPhone1:            "โทรศัพท์ 1",
  ctPhone2:            "โทรศัพท์ 2",
  ctMobile:            "มือถือ",
  ctEmail:             "อีเมล",
  ctHoursEn:           "เวลาทำการ (อังกฤษ)",
  ctHoursTh:           "เวลาทำการ (ไทย)",
  ctAddressEn:         "ที่อยู่ (อังกฤษ)",
  ctAddressTh:         "ที่อยู่ (ไทย)",
  ctFacebook:          "URL Facebook",
  ctInstagram:         "URL Instagram",
  ctLine:              "URL LINE",
  ctYoutube:           "URL YouTube",
  ctTiktok:            "URL TikTok",
  ctSocialHint:        "กรอก URL เต็ม (https://…)",
  ctSections:          "ส่วน",

  // ── Footer editor ───────────────────────────────────────────────────────
  footerLoading:       "กำลังโหลดส่วนท้าย…",
  ftSecBrand:          "ข้อความแบรนด์",
  ftSecBrandDesc:      "ชื่อบริษัท แท็กไลน์ คำอธิบาย หัวข้อจดหมายข่าว ปีลิขสิทธิ์",
  ftSecServices:       "รายการบริการ",
  ftSecServicesDesc:   "คอลัมน์บริการในส่วนท้าย — รายการป้ายกำกับที่แก้ไขได้",
  ftSecLinks:          "ลิงก์ด่วน",
  ftSecLinksDesc:      "คอลัมน์นำทาง — แก้ไขป้ายกำกับและเส้นทางได้",
  ftSecContact:        "ข้อมูลติดต่อ & โซเชียล",
  ftSecContactDesc:    "แชร์กับแท็บติดต่อ — แก้ไขที่นั่น",
  ftInfoOnly:          "ข้อมูลเท่านั้น",
  ftCompanyName:       "ชื่อบริษัท",
  ftTagline:           "แท็กไลน์",
  ftDescEn:            "คำอธิบาย (อังกฤษ)",
  ftDescTh:            "คำอธิบาย (ไทย)",
  ftNewsletterHead:    "หัวข้อจดหมายข่าว",
  ftCopyrightYear:     "ปีลิขสิทธิ์",
  ftServicesHint:      "ป้ายกำกับในคอลัมน์บริการ — แสดงเท่านั้น ไม่มีลิงก์",
  ftServiceName:       "ชื่อบริการ",
  ftAddService:        "เพิ่มบริการ",
  ftLinksHint:         "ลิงก์ด่วน ใช้เส้นทางภายใน (/about) หรือ URL เต็ม ป้ายกำกับทั้งไทยและอังกฤษแสดงตามการตั้งค่าภาษา",
  ftLinkLabelEn:       "ป้ายกำกับ (อังกฤษ)",
  ftLinkLabelTh:       "ป้ายกำกับ (ไทย)",
  ftLinkUrl:           "URL / เส้นทาง",
  ftAddLink:           "เพิ่มลิงก์",
  ftContactHead:       "ข้อมูลติดต่อ & โซเชียลมีเดีย",
  ftContactBody:       "หมายเลขโทรศัพท์ อีเมล ที่อยู่ เวลาทำการ และ URL โซเชียลมีเดียในส่วนท้ายแชร์กับหน้าติดต่อ — อัปเดตในแท็บ \"ติดต่อ\" และส่วนท้ายจะอัปเดตโดยอัตโนมัติ",
  ftContactLink:       "ไปที่ คอนเทนต์ → แท็บติดต่อ → ข้อมูลติดต่อและโซเชียลลิงก์",

  // ── Branding editor ─────────────────────────────────────────────────────
  brandingTitle:       "โลโก้เว็บไซต์",
  brandingDesc:        "แสดงในแถบนำทางและส่วนท้ายทุกหน้า แนะนำ: PNG สี่เหลี่ยม ขนาดอย่างน้อย 200×200 px",
  brandingLoadingLogo: "กำลังโหลด…",
  brandingCustomLogo:  "โลโก้กำหนดเอง (จากที่เก็บข้อมูล)",
  brandingDefaultLogo: "โลโก้เริ่มต้น  ·  /F2.png",
  brandingUploadBtn:   "อัปโหลดโลโก้ใหม่",
  brandingUploading:   "กำลังอัปโหลด…",
  brandingSaving:      "กำลังบันทึก…",
  brandingRevert:      "กลับเป็นค่าเริ่มต้น",
  brandingHint:        "PNG, JPEG, WebP, หรือ SVG · สูงสุด 5 MB การเปลี่ยนแปลงมีผลทันที ไม่ต้องบันทึกแยก",
  brandingAlt:         "ตัวอย่างโลโก้",
  toastLogoUpdated:    "อัปเดตโลโก้แล้ว — แถบนำทางและส่วนท้ายจะแสดงโลโก้ใหม่",
  toastLogoReverted:   "กลับเป็นโลโก้เริ่มต้นแล้ว",
  toastLogoSize5:      "รูปภาพต้องมีขนาดไม่เกิน 5 MB",
  toastLogoSaveFail:    "บันทึกไม่สำเร็จ",
  toastLogoUploadFail:  (msg: string) => `อัปโหลดไม่สำเร็จ: ${msg}`,
  brandingRevertConfirm: "กลับเป็นโลโก้เริ่มต้น (/F2.png)?",

  // ── Category manager ────────────────────────────────────────────────────
  catTitle:            "จัดการหมวดหมู่",
  catDesc:             "หมวดหมู่สร้างแท็บกรองในหน้าแรกโดยอัตโนมัติ การเปลี่ยนชื่อหมวดหมู่จะอัปเดตสินค้าที่ใช้หมวดหมู่นั้นทั้งหมด",
  catWarning:          "ลบหมวดหมู่ได้เฉพาะเมื่อไม่มีสินค้าในหมวดนั้น กรุณาย้ายสินค้าก่อนในส่วนสินค้า",
  catHeader:           (n: number) => `หมวดหมู่ (${n} รายการ)`,
  catDragHint:         "↕ ลากเพื่อเรียงลำดับ",
  catRenaming:         "กำลังเปลี่ยนชื่อ…",
  catSave:             "บันทึก",
  catCancel:           "ยกเลิก",
  catClickRename:      "คลิกเพื่อเปลี่ยนชื่อ",
  catVisHide:          "แสดง — คลิกเพื่อซ่อน",
  catVisShow:          "ซ่อน — คลิกเพื่อแสดง",
  catHasProducts:      "มีสินค้าอยู่",
  catDeleteTitle:      "ลบหมวดหมู่",
  catPlaceholder:      "ชื่อหมวดหมู่ใหม่...",
  catAdding:           "กำลังเพิ่ม…",
  catAddBtn:           "เพิ่มหมวดหมู่",
  catProductCount:     (n: number) => `${n} สินค้า`,
  catAddedMsg:         (name: string) => `✓ "${name}" เพิ่มแล้ว`,
  catRenamedMsg:       (n: number) => `✓ เปลี่ยนชื่อแล้ว — อัปเดต ${n} สินค้า`,
  catDeletedMsg:       (name: string) => `✓ "${name}" ลบแล้ว`,
  catExistsErr:        (name: string) => `"${name}" มีอยู่แล้ว`,
  catAddFail:          "เพิ่มหมวดหมู่ไม่สำเร็จ",
  catRenameFail:       "เปลี่ยนชื่อไม่สำเร็จ",
  catDeleteFail:       "ลบหมวดหมู่ไม่สำเร็จ",
  catVisFail:          "อัปเดตการแสดงผลไม่สำเร็จ",
  catOrderFail:        "บันทึกลำดับไม่สำเร็จ",
  catDeleteConfirm:    (name: string) => `ลบหมวดหมู่ "${name}"? การดำเนินการนี้ไม่สามารถเลิกทำได้`,

  // ── Tag manager ─────────────────────────────────────────────────────────
  tagTitle:            "จัดการแท็ก",
  tagDesc:             "แท็กสร้างชิปกรองในหน้าแคตาล็อก การเปลี่ยนชื่อแท็กจะอัปเดตสินค้าที่ใช้แท็กนั้นทั้งหมด",
  tagWarning:          "ลบแท็กได้เฉพาะเมื่อไม่มีสินค้าใช้แท็กนั้น กรุณาย้ายสินค้าก่อน",
  tagHeader:           (n: number) => `แท็ก (${n} รายการ)`,
  tagRenaming:         "กำลังเปลี่ยนชื่อ…",
  tagSave:             "บันทึก",
  tagCancel:           "ยกเลิก",
  tagClickRename:      "คลิกเพื่อเปลี่ยนชื่อ",
  tagHasProducts:      "มีสินค้าอยู่",
  tagDeleteTitle:      "ลบแท็ก",
  tagPlaceholder:      "ชื่อแท็กใหม่...",
  tagAdding:           "กำลังเพิ่ม…",
  tagAddBtn:           "เพิ่มแท็ก",
  tagProductCount:     (n: number) => `${n} สินค้า`,
  tagAddedMsg:         (name: string) => `✓ "${name}" เพิ่มแล้ว`,
  tagRenamedMsg:       (n: number) => `✓ เปลี่ยนชื่อแล้ว — อัปเดต ${n} สินค้า`,
  tagDeletedMsg:       (name: string) => `✓ "${name}" ลบแล้ว`,
  tagExistsErr:        (name: string) => `"${name}" มีอยู่แล้ว`,
  tagAddFail:          "เพิ่มแท็กไม่สำเร็จ",
  tagRenameFail:       "เปลี่ยนชื่อไม่สำเร็จ",
  tagDeleteFail:       "ลบแท็กไม่สำเร็จ",
  tagDeleteConfirm:    (name: string) => `ลบแท็ก "${name}"? การดำเนินการนี้ไม่สามารถเลิกทำได้`,

  // ── Profile ─────────────────────────────────────────────────────────────
  profilePwCard:       "รหัสผ่าน",
  profileSessionCard:  "เซสชัน",
  profileAdminAccounts:"บัญชีแอดมิน",
  profileAddAdminLabel:"เพิ่มแอดมิน",
  profileRoleBadge:    "แอดมิน",
  profileYouBadge:     "คุณ",
  profilePendingBadge: "รอสมัครสมาชิก",
  profilePendingTitle: (email: string) => `${email} ยังไม่มีบัญชี — สมัครที่หน้า /signup ด้วยอีเมลนี้ก่อนจึงจะเข้าสู่ระบบได้`,
  profileCopyInstructions: "คัดลอกคำแนะนำ",
  profileNeverSignedIn: "ยังไม่เคยเข้าใช้งาน",
  profileLastSignIn:   (relativeTime: string) => `เข้าใช้งานล่าสุด ${relativeTime}`,
  timeJustNow:         "เมื่อสักครู่",
  timeHoursAgo:        (n: number) => `${n} ชั่วโมงที่แล้ว`,
  timeDaysAgo:         (n: number) => `${n} วันที่แล้ว`,
  timeMonthsAgo:       (n: number) => `${n} เดือนที่แล้ว`,
  timeYearsAgo:        (n: number) => `${n} ปีที่แล้ว`,
  profileNewPw:        "รหัสผ่านใหม่",
  profileConfirmPw:    "ยืนยันรหัสผ่าน",
  profileSignedAs:     "เข้าสู่ระบบในฐานะ",
  profileSignOutDesc:  "ออกจากระบบทุกอุปกรณ์",
  profileSavingPw:     "กำลังบันทึก…",
  profileUpdatePw:     "เปลี่ยนรหัสผ่าน",
  profileSignOut:      "ออกจากระบบ",
  profileRemove:       "นำออก",
  profileCancel:       "ยกเลิก",
  profileAdding:       "กำลังเพิ่ม…",
  profileAddBtn:       "เพิ่มแอดมิน",
  profileRemoveTitle:  "นำแอดมินออก",
  toastAdminAdded:     (email: string) => `${email} ถูกเพิ่มเป็นแอดมินแล้ว — แจ้งให้เขาสมัครสมาชิกที่หน้า /signup ด้วยอีเมลนี้ เพื่อให้เข้าสู่ระบบได้`,
  toastInstructionsCopied: "คัดลอกคำแนะนำแล้ว",
  toastCopyFail:       "คัดลอกไม่สำเร็จ",
  toastAdminInvited:   (email: string) => `ส่งคำเชิญไปยัง ${email} แล้ว — กรุณาตรวจสอบอีเมล`,
  toastAdminRemoved:   (email: string) => `${email} ถูกนำออกแล้ว`,
  toastPwUpdated:      "อัปเดตรหัสผ่านสำเร็จ",
  toastAdminAddFail:   "เพิ่มแอดมินไม่สำเร็จ",
  toastAdminRemoveFail:(email: string) => `ลบ ${email} ไม่สำเร็จ`,
  toastPwMismatch:     "รหัสผ่านไม่ตรงกัน",
  toastPwTooShort:     "รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร",
  toastPwFail:         "อัปเดตรหัสผ่านไม่สำเร็จ",
  profilePwPlaceholder:"อย่างน้อย 6 ตัวอักษร",
  profilePwRepeat:     "ยืนยันรหัสผ่าน",

  // ── Server-side errors (profile/actions.ts) ──────────────────────────────
  errEmailRequired:    "กรุณากรอกอีเมล",
  errEmailExists:      "อีเมลนี้เป็นแอดมินอยู่แล้ว",
  errCannotRemoveSelf: "ไม่สามารถลบตัวเองได้ — กรุณาเพิ่มแอดมินคนอื่นก่อน",
  errInviteFailed:     "เพิ่มแอดมินไม่สำเร็จ — ส่งคำเชิญไม่ได้",
  errPwTooShort:       "รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร",
  errCatDeleteBlocked: (n: number) => `ไม่สามารถลบได้ — มีสินค้า ${n} รายการใช้หมวดหมู่นี้ กรุณาเปลี่ยนหมวดหมู่สินค้าก่อน`,
  errTagDeleteBlocked: (n: number) => `ไม่สามารถลบได้ — มีสินค้า ${n} รายการใช้แท็กนี้ กรุณาเปลี่ยนแท็กสินค้าก่อน`,

  // ── Auth / reset-password ────────────────────────────────────────────────
  resetVerifying:      "กำลังตรวจสอบลิงก์รีเซ็ต…",
  resetSuccess:        "ตั้งรหัสผ่านสำเร็จ!",
  resetSuccessDesc:    "คุณสามารถเข้าสู่ระบบด้วยอีเมลและรหัสผ่านใหม่ได้แล้ว",
  resetGoSignIn:       "ไปหน้าเข้าสู่ระบบ",
  resetFormHead:       "ตั้งรหัสผ่านใหม่",
  resetFormSub:        "เลือกรหัสผ่านเพื่อเปิดใช้การเข้าสู่ระบบด้วยอีเมลสำหรับบัญชีของคุณ",
  resetNewPw:          "รหัสผ่านใหม่",
  resetConfirmPw:      "ยืนยันรหัสผ่าน",
  resetHidePw:         "ซ่อนรหัสผ่าน",
  resetShowPw:         "แสดงรหัสผ่าน",
  resetSaving:         "กำลังบันทึก…",
  resetSetBtn:         "ตั้งรหัสผ่าน",
  resetErrShort:       "รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร",
  resetErrMismatch:    "รหัสผ่านไม่ตรงกัน",
  resetBack:           "← กลับไปหน้าเข้าสู่ระบบ",
} as const;
